### ISSUE TITLE
ros2_shm_msgs不会配置

### ISSUE THREAD

**Issue by HaozhongXu** [lonelygsh/Ascend_USBCamera_yolov5#1]
lonelygsh你好！
看了你的CANN训练营的展示，真的很令人激动，尤其是对目标检测的优化过程！
我手头有一块Atlas 200i DK A2，使用RC3版本，也安装了ros2 humble版本，想要复现你的过程，尽管你的readme已经足够详细了，但因为我的了解甚浅，动手能力太差，我在:~/test/zero-copy_ws/Ascend_USBCamera_yolov5-master/Ascend310B/src/zero_copy$下面git clone了ros2_shm_msgs，但是不会选择不管是在Asnend310B还是zero_copy下面colcon build都会报错。
<img width="596" alt="e3b0014a476e7e0bfb9e83a4a43b8a8" src="https://github.com/lonelygsh/Ascend_USBCamera_yolov5/assets/129271489/c0263fc9-25f9-4e87-813b-ab11e6035d89">
恳请你可以出一份比较详细的如何运行你的文档的配置信息吗？
希望我以后可以变得和你一样厉害，一样lonely，哈哈哈。

**Comment by HaozhongXu** [comment]
在git clone shm_msgs包后，mkdir build, cmake.., make ,sudo make intall,在Ascend310B进行编译，报错
![image](https://github.com/lonelygsh/Ascend_USBCamera_yolov5/assets/129271489/70da6d74-2eb5-4b86-9a03-c57efda490c1)

**Comment by lonelygsh** [comment]
> lonelygsh你好！ 看了你的CANN训练营的展示，真的很令人激动，尤其是对目标检测的优化过程！ 我手头有一块Atlas 200i DK A2，使用RC3版本，也安装了ros2 humble版本，想要复现你的过程，尽管你的readme已经足够详细了，但因为我的了解甚浅，动手能力太差，我在:~/test/zero-copy_ws/Ascend_USBCamera_yolov5-master/Ascend310B/src/zero_copy$下面git clone了ros2_shm_msgs，但是不会选择不管是在Asnend310B还是zero_copy下面colcon build都会报错。 <img alt="e3b0014a476e7e0bfb9e83a4a43b8a8" width="596" src="https://private-user-images.githubusercontent.com/129271489/320252821-c0263fc9-25f9-4e87-813b-ab11e6035d89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MzU4MjEsIm5iZiI6MTcxMjUzNTUyMSwicGF0aCI6Ii8xMjkyNzE0ODkvMzIwMjUyODIxLWMwMjYzZmM5LTI1ZjktNGU4Ny04MTNiLWFiMTFlNjAzNWQ4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOFQwMDE4NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYWM2NjRlMDdiOWYzMzE1MGJmYTBmYzg3ODkzN2NlOTAwNDM3NTYyYjEwM2M0ZjZiM2EzNWQwOTlhYzk4NzY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.J3qBWTdgkcbzdDmdaplDlkdlb3haTSwWFfqC8KpZz0I"> 恳请你可以出一份比较详细的如何运行你的文档的配置信息吗？ 希望我以后可以变得和你一样厉害，一样lonely，哈哈哈。

这个报错没有找到iceoryx_poshConfig.cmake。可能是因为你没有安装iceoryx这个库，https://github.com/eclipse-iceoryx/iceoryx，你可以在这个网站进行下载编译安装。iceoryx是ROS2的零拷贝RMW的中间件，对于humble版本的ROS2，对应默认的DDS是eProsima’s Fast DDS，对于Foxy版本的ROS2，对应默认的DDS是eProsima’s Fast DDS，并没有默认使用iceoryx为中间件版本的ROS2，所以你需要手动编译安装iceoryx。

**Comment by lonelygsh** [comment]
> 在git clone shm_msgs包后，mkdir build, cmake.., make ,sudo make intall,在Ascend310B进行编译，报错 ![image](https://private-user-images.githubusercontent.com/129271489/320284927-70da6d74-2eb5-4b86-9a03-c57efda490c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MzU4MjEsIm5iZiI6MTcxMjUzNTUyMSwicGF0aCI6Ii8xMjkyNzE0ODkvMzIwMjg0OTI3LTcwZGE2ZDc0LTJlYjUtNGI4Ni05YTAzLWM1N2VmZGE0OTBjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOFQwMDE4NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZjQyM2FiN2ViNWMwMTI4ZTEzMzRmNzBkYmI0ZTFkOWQzZTViMmU1MDU0NzA5NmRhZDBiZWI3NDkzN2VhMDkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vFG5cOCZ4XmzF6xReEgmV7VHgzfUPlde_TIQ_Mo3vN0)

这个报错是因为你没有安装acllite库，这个库在orangepi AIpro这块开发板的预装系统中就已经安装好了，我不确定你那一块开发板中是否有安装，如果没有安装，你可以在https://gitee.com/ascend/ACLLite 这个网站中下载编译安装，然后别忘了在你项目中的cmakelists中添加这个库。

**Comment by XuLearner6** [comment]
你好，gsh！
    最近事情有点多，但我还是在一直尝试在Atlas 200i DK A2上复现这个项目，ACLlite也安装成功了，尽管它一开始不起作用，可是重启后尽然生效了，，，目前报这个错误，原谅我这么菜，我真的琢磨了好久实在解决不了才会向您求助，虽然解决方法可能会很简单，也劳烦您帮我一下，我也在做文档，成功之后也可以作为笔记提交，感谢！
<img width="563" alt="099ab2c56303e0870ae082dc8da5d3f" src="https://github.com/lonelygsh/Ascend_USBCamera_yolov5/assets/129271489/15b8b79f-c74c-47a8-b3b0-4db0b99bc74d">

**Comment by lonelygsh** [comment]
这个报错的原因是，我在my_interfaces这个功能包中定义了yolov5检测框的ROS2消息，face_recognition使用到了这个消息，所以应该在colcon build之前，先对my_interfaces进行编译，可以使用colcon build --packages-select my_interfaces




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lonelygsh/Ascend_USBCamera_yolov5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月9日(星期二) 上午10:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lonelygsh/Ascend_USBCamera_yolov5] ros2_shm_msgs不会配置 (Issue #1)





 
你好，gsh！
 最近事情有点多，但我还是在一直尝试在Atlas 200i DK A2上复现这个项目，ACLlite也安装成功了，尽管它一开始不起作用，可是重启后尽然生效了，，，目前报这个错误，原谅我这么菜，我真的琢磨了好久实在解决不了才会向您求助，虽然解决方法可能会很简单，也劳烦您帮我一下，我也在做文档，成功之后也可以作为笔记提交，感谢！
 099ab2c56303e0870ae082dc8da5d3f.png (view on web)
